config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  namespace :admin do
    resources :accounts
    resources :conferences
    resources :papers
    resources :reviews
    resources :tracks
    resources :committees
    resources :users
    resources :super_accounts

    root to: "accounts#index"
  end

  resources :tracks
  resources :committees do
    get "showid", on: :member
    get "members", on: :member
    resources :papers, only: [:new, :create]
  end
  devise_for :accounts,  :controllers => { :registrations => 'registrations' }
  resources :users, only: [:edit, :update]
  resources :conferences do
    get "showid", on: :member
    resources :tracks, only: [:new, :create]
    resources :committees, only: [:new, :create]
  end
  resources :reviews do
    get "showid", on: :member
  end
  resources :papers do
    put 'accept', on: :member
    post 'accept', on: :member
    put 'decline', on: :member
    post 'decline', on: :member
    put 'rate', on: :member
    post 'rate', on: :member
    get "showid", on: :member
    resources :reviews, only: [:new, :create]
  end
  root "conferences#index"
  get "reviews/new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conference.rb
class Conference < ApplicationRecord
    validates :name, presence: true# Make sure the owner's name is present.
    validates :name, uniqueness: true
    has_many:committees
    has_many :tracks
end

app/controllers/admin/conferences_controller.rb
module Admin
  class ConferencesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Conference.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Conference.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_action :set_conference, only: [:show, :edit, :update, :destroy]

  # GET /conferences
  # GET /conferences.json
  def index
    @state = false
    @conferences = Conference.all

    respond_to do |format|
      format.html {
          if (params[:spa] && params[:spa] == "true")
              render 'index_spa'
          # the else case below is by default
          # else
          #    render 'index'
          end
      }
      format.json {render json: @conferences}
    end
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
  end
  
  def showid
    authenticate_account!
    @conferences = Conference.all
  end

  # GET /conferences/new
  def new
    authenticate_account!
    @conference = Conference.new
  end

  # GET /conferences/1/edit
  def edit
    authenticate_account!
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(conference_params)
    @conference.chairid = current_account.id
    @conference.approved = false
    respond_to do |format|
      if @conference.save
        format.html { redirect_to new_conference_committee_path(@conference), notice: 'Conference was successfully created.' }
        format.json { render :show, status: :created, location: @conference }
      else
        format.html { render :new }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conferences/1
  # PATCH/PUT /conferences/1.json
  def update
    respond_to do |format|
      if @conference.update(conference_params)
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { render :show, status: :ok, location: @conference }
      else
        format.html { render :edit }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference = Conference.find(params[:id])
   @conference.committees.each do |committee| 
      if(committee.conference == @conference)
        committee.destroy
      end
   end
    @conference.destroy
    respond_to do |format|
      format.html { redirect_to conferences_url, notice: 'Conference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = Conference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
      params.require(:conference).permit(:name)
    end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/_form.html.erb
<%= form_for(conference) do |f| %>
  <% if conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% conference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conferences/edit.html.erb
<br />
<br />
<h1>Editing Conference</h1>
<% @state=true %>
    <% if(@conference.chairid == current_account.id) %>
        <%= render 'form', conference: @conference %>

        <%= link_to 'Show', @conference %> |
        <%= link_to 'Back', conferences_path %>
        <% @state = false %>
    <% end %>
<% if(@state) %>
    <h3>Silly hacker this is not for you.</h3>
<% end %>

app/views/conferences/index.html.erb
<p id="notice"><%= notice %></p>

<br />
<br />
<h1>Conferences</h1>


<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conferences.each do |conference| %>
      <tr>
        <% @state =false %>
        <% if current_account !=nil%>
        <% conference.tracks.each do |track| %>
          <% if(track.userid == current_account.id && track.role == "Chair") %>
            <% @state = true %>
          <% end %>
        <% end %>
        <% end %>
        <td><%= conference.name %></td>
        <td><%= link_to 'Show', conference %></td>
        <% if(@state) %>
          <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
          <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conference', new_conference_path %>

app/views/conferences/index_spa.html.erb
<p id="notice"><%= notice %></p>

<%= react_component("Catalog", props: {catalog: @conferences}, prerender: false) %>

app/views/conferences/new.html.erb
<br />
<br />
<h1>New Conference</h1>

<%= render 'form', conference: @conference %>

<%= link_to 'Back', conferences_path %>

app/views/conferences/show.html.erb
<br />
<br />
<p id="notice"><%= notice %></p>
<h1> Conference: <%= @conference.name %></h1>
<% @state3 = false %>
<% if(current_account != nil) %>
  <% if (@conference.chairid == current_account.id) %>
      <% @state3 =true %>
  <% end %>
<% end %>
<% if (@state3) %>
      <%= link_to 'Add Committee ', new_conference_committee_path(@conference) %>
  <% end %>
           
        
<table class = "table table-bordered table-striped">
    <thead>
        <tr>
            <th>Committee Name</th>
            <th>Papers</th>
            <th>Tracks</th>
            <th>Number of members</th>

            <% if (@state3) %>
                <th>Manage</th>
          
                <th>Delete</th>
            <% end %>
        </tr>
    </thead>
    <tbody> 
     <% @conference.committees.each do |committee| %>
     <tr>
        <td><%= committee.name %></td>
       <td><%= link_to 'Papers', committee %></td>
       <td><%= link_to 'Tracks', members_committee_path(committee) %></td>
        <td><%= committee.tracks.count + 2 %></td>
        <% if (@state3) %>
            <td><%= link_to 'Edit', edit_committee_path(committee) %></td>
            <td><%= link_to 'Destroy', committee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
     </tr>
     <% end %>
 </tbody>
</tbody>
<%= link_to 'Join Conference ', new_conference_track_path(@conference) %>
<%= link_to 'Back ', conferences_path %>

app/views/conferences/showid.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<br />
<h1>Conferences</h1>

<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conferences.each do |conference| %>
      <tr>
        <% if conference.chairid == current_account.id %>
          <td><%= conference.name %></td>
          <td><%= link_to 'Show', conference %></td>
          <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
          <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>