config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  namespace :admin do
    resources :accounts
    resources :conferences
    resources :papers
    resources :reviews
    resources :tracks
    resources :committees
    resources :users
    resources :super_accounts

    root to: "accounts#index"
  end

  resources :tracks
  resources :committees do
    get "showid", on: :member
    get "members", on: :member
    resources :papers, only: [:new, :create]
  end
  devise_for :accounts,  :controllers => { :registrations => 'registrations' }
  resources :users, only: [:edit, :update]
  resources :conferences do
    get "showid", on: :member
    resources :tracks, only: [:new, :create]
    resources :committees, only: [:new, :create]
  end
  resources :reviews do
    get "showid", on: :member
  end
  resources :papers do
    put 'accept', on: :member
    post 'accept', on: :member
    put 'decline', on: :member
    post 'decline', on: :member
    put 'rate', on: :member
    post 'rate', on: :member
    get "showid", on: :member
    resources :reviews, only: [:new, :create]
  end
  root "conferences#index"
  get "reviews/new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/committee.rb
class Committee < ApplicationRecord
    belongs_to :conference
    belongs_to :user
    has_many :tracks
    has_many :papers
end

app/controllers/admin/committees_controller.rb
module Admin
  class CommitteesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Committee.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Committee.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_action :set_committee, only: [:show, :edit, :update, :destroy]

  # GET /committees
  # GET /committees.json
  def index
    @committees = Committee.all
  end

  # GET /committees/1
  # GET /committees/1.json
  def show
  end
  
  def showid
    @committees = Committee.all
  end

  def members
    @committee = Committee.find_by_id(params[:id])
  
  end
  # GET /committees/new
  def new
    @conference = Conference.find_by_id(params[:conference_id])
    @committee = Committee.new
  end

  # GET /committees/1/edit
  def edit
  end

  # POST /committees
  # POST /committees.json
  def create
    @committee = Committee.new(committee_params)
    
    
      if @committee.save
        @conference = @committee.conference
        if @conference.chairid != current_account.id
          @committee.destroy
          redirect_to @conference, notice: "You are not the chair of this conference."
        else if @conference.chairid == @committee.user.id
          @committee.destroy
          redirect_to @conference, notice: "You can't make yourself a PC chair in your own conference."
        else
          respond_to do |format|
          format.html { redirect_to @committee, notice: 'Committee was successfully created.' }
          format.json { render :show, status: :created, location: @committee }
          end
        end
        end
      else
        respond_to do |format|
        format.html { render :new }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /committees/1
  # PATCH/PUT /committees/1.json
  def update
    respond_to do |format|
      if @committee.update(committee_params)
        format.html { redirect_to @committee, notice: 'Committee was successfully updated.' }
        format.json { render :show, status: :ok, location: @committee }
      else
        format.html { render :edit }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /committees/1
  # DELETE /committees/1.json
  def destroy
    @committee.papers.each do |paper| 
        paper.destroy
   end
   @committee.tracks.each do |track| 
        track.destroy
   end
    @committee.destroy
    respond_to do |format|
      format.html { redirect_to conferences_path, notice: 'Committee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_committee
      @committee = Committee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def committee_params
      params.require(:committee).permit(:name, :user_id, :conference_id)
    end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/_form.html.erb
<%= form_for([conference,committee]) do |f| %>
  <% if committee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(committee.errors.count, "error") %> prohibited this committee from being saved:</h2>

      <ul>
      <% committee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  
   <div class="field">
    <%= f.label :user_id %>
    <%= "Person to be PC Chair." %>
       <%= f.collection_select :user_id, User.order(:name),:id,:name, include_blank: false %>
  </div>
  

  <div class="field">
    <%= f.label :conference_id %>
    <% if conference != nil%>
    <%= f.select(:conference_id, options_for_select([[conference.name, conference.id]])) %>
    <% else %>
      <%= f.collection_select :conference_id, Conference.all, :id, :name, include_blank: false %>
    <% end %>
    <% f.text_field :conference_id %>
  </div>
  
 


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/committees/_form2.html.erb
<%= form_for(committee) do |f| %>
  <% if committee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(committee.errors.count, "error") %> prohibited this committee from being saved:</h2>

      <ul>
      <% committee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  
   <div class="field">
    <%= f.label :user_id %>
    <%= " that is PC Chair." %>
       <%= committee.user.name %>
  </div>
  

  <div class="field">
    <%= f.label :conference_id %>
    <%= committee.conference.name %>
  </div>
  
 


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/committees/edit.html.erb
<h1>Editing Committee</h1>
<% @state = true%>
<% if @committee.conference.chairid == current_account.id %>
    <%= render 'form2', committee: @committee %>
    <% @state = false %>
    <%= link_to 'Show', @committee %>
    <%= link_to 'Back', committees_path %>
<% end %>
<% if(@state) %>
    <h3>Silly hacker this is not for you.</h3>
<% end %>

app/views/committees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Committees</h1>
<% if current_account.accountable_type == "SuperAccount" %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Conference</th>
      <th>PC Chair</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @committees.each do |committee| %>
      <tr>
        <td><%= committee.name %></td>
        <td><%= committee.conference %></td>
        <td><%= committee.user.name %></td>
        <td><%= link_to 'Show', committee %></td>
        <td><%= link_to 'Edit', edit_committee_path(committee) %></td>
        <td><%= link_to 'Destroy', committee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Committee', new_committee_path %>
<% else %>
    <h3>Admins only.</h3>
<% end %>

app/views/committees/members.html.erb
<br />
<br />
<p id="notice"><%= notice %></p>
<h1> Committee: <%= @committee.name %> of Conference: <%= @committee.conference.name %></h1>
<% @state3 = false %>
<% if(current_account != nil) %>
  <% if (@committee.user.id == current_account.id) %>
      <% @state3 =true %>
  <% end %>
<% end %>
 <% @state3 =false %>
<table class = "table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Role</th>
            <% if (@state1) %>
                <th>Manage</th>
            <% end %>
        </tr>
    </thead>
    <tbody> 
     <tr>
         <% if @committee.conference.chairid > 6 %>
           <% @user = User.find_by_id(@committee.conference.chairid - 1) %>
         <% else %>
           <% @user = User.find_by_id(@committee.conference.chairid) %>
         <% end %>
         <% if @user != nil %>
           <td><%= @user.name %></td>
         <% else %>
           <td><%= "None" %></td>
         <% end %>
       <td>Conference Chair</td>
       
     </tr>
     <tr>
         <% @user = @committee.user %>
         <% if @user != nil %>
           <td><%= @user.name %></td>
         <% else %>
           <td><%= "None" %></td>
         <% end %>
       <td>PC Chair</td>
     </tr>
  <% @committee.tracks.each do |track| %>
     <tr>
         <% if track.userid > 6 %>
           <% @user = User.find_by_id(track.userid - 1)%>
         <% else %>
           <% @user = User.find_by_id(track.userid)%>
         <% end %>
        <% if @user != nil %>
       <td><%= @user.name %></td>
       <td><%= track.role %></td>
        <% if (@state3) %>
            <td><%= "Accepted" %></td>
        <% end %>
        <% end %>
     </tr>
    <% end %>
 </tbody>
</tbody>
<%= link_to 'Back', @committee.conference %>

app/views/committees/new.html.erb
<h1>New Committee</h1>

<%= render 'form', committee: @committee, conference: @conference %>

<%= link_to 'Back', committees_path %>

app/views/committees/show.html.erb
<br />
<br />
<p id="notice"><%= notice %></p>
<h1> Committee: <%= @committee.name %></h1>
<% @state3 = false %>
<% if(current_account != nil) %>
  <% if (@committee.conference.chairid == current_account.id) %>
      <% @state3 =true %>
  <% end %>
<% end %>

            <% @state1 =false %>
            <% @state2 =false %>
            <% @state4 =false %>
            <% if(current_account != nil) %>
                <% if (@committee.user.id == current_account.id) %>
                    <% @state1 =true %>
                <% end %>
            <% if(@state1 == false) %>
            <% @committee.tracks.each do |track| %>
                <% if (track.userid == current_account.id && track.role == "PC Member") %>
                    <% @state2 =true %>
                    <% break %>
                <% end %>
                <% if (track.userid == current_account.id && track.role == "Author") %>
                    <% @state4 =true %>
                    <% break %>
                <% end %>
            <% end %>
            <% end %>
<% if (@state4)%>
                <%= link_to 'New Paper ', new_committee_paper_path(@committee) %>
<% end %>
<table class = "table table-bordered table-striped">
    <thead>
        <tr>
            <th>Paper Title</th>
            <th>Author</th>
            <th>Download Link</th>
            <th>Reviews</th>
            <th>Status</th>
            <% if (@state1) %>
                <th>Manage Paper</th>
            <% end %>
            <% if (@state2) %>
                <th>Review Link</th>
            <% end %>
            
        </tr>
    </thead>
    <tbody> 
  <% @committee.papers.each do |paper| %>
     <tr>
       <td><%= paper.title %></td>
       <td><%= paper.author %></td>
        <td><%= link_to "Download Paper", paper.attachment_url %></td>
        <td><%= link_to 'Reviews', paper %></td>
        <% if (paper.rating >= 5.5 and paper.accepted) %>
            <td><%= "Accepted with rating of " + "%05.2f" % paper.rating %></td>
        <% else %>
            <td><%= "Not accepted with rating of " + "%05.2f" % paper.rating %></td>
        <% end %>
        <% if (@state1 && paper.accepted == false) %>
        <td><%= button_to "Accept",  accept_paper_path(id = paper.id), class: "btn btn-danger", data: { confirm: "Are you sure that you wish to accept #{paper.title}?"} %></td>
        <% else if @state1%>
        <td><%= button_to "Decline",  decline_paper_path(id = paper.id), class: "btn btn-danger", data: { confirm: "Are you sure that you wish to decline #{paper.title}?"} %></td>
        <% end %>
        <% end %>
        <% if (@state2) %>
        <td><%= link_to "Review paper", new_paper_review_path(paper) %></td>
        <% end %>
        
     </tr>
    <% end %>
 </tbody>
</tbody>
<% end %>
<%= link_to 'Back', @committee.conference %>

app/views/committees/showid.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<br />
<h1>Committees</h1>


<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Conference</th>
      <th>PC Chair</th>
      
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @committees.each do |committee| %>
      <tr>
          <% if committee.user.id == current_account.id || committee.conference.chairid == current_account.id %>
              <td><%= committee.name %></td>
              <td><%= committee.conference.name %></td>
              <td><%= committee.user.name %></td>
              <td><%= link_to 'Show', committee %></td>
              <% if committee.conference.chairid == current_account.id %>
                  <td><%= link_to 'Edit', edit_committee_path(committee) %></td>
                  <td><%= link_to 'Destroy', committee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              
              <% end %>
          <% end %>
  <div class>
  <%= flash[:notice] %>
  </div>
<% end %>
<br>