config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  namespace :admin do
    resources :accounts
    resources :conferences
    resources :papers
    resources :reviews
    resources :tracks
    resources :committees
    resources :users
    resources :super_accounts

    root to: "accounts#index"
  end

  resources :tracks
  resources :committees do
    get "showid", on: :member
    get "members", on: :member
    resources :papers, only: [:new, :create]
  end
  devise_for :accounts,  :controllers => { :registrations => 'registrations' }
  resources :users, only: [:edit, :update]
  resources :conferences do
    get "showid", on: :member
    resources :tracks, only: [:new, :create]
    resources :committees, only: [:new, :create]
  end
  resources :reviews do
    get "showid", on: :member
  end
  resources :papers do
    put 'accept', on: :member
    post 'accept', on: :member
    put 'decline', on: :member
    post 'decline', on: :member
    put 'rate', on: :member
    post 'rate', on: :member
    get "showid", on: :member
    resources :reviews, only: [:new, :create]
  end
  root "conferences#index"
  get "reviews/new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/paper.rb
class Paper < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  belongs_to :committee
  validates :title,  :attachment, presence: true# Make sure the owner's name is present.
  validates :title, uniqueness: true
  validates :attachment, allow_blank: true, format: {
    with: %r{\.(doc|docx|pdf)\Z}i,
    message: 'must be a URL for DOC, DOCX or PDF image.'
    }
  has_many:reviews


end

app/controllers/admin/papers_controller.rb
module Admin
  class PapersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Paper.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Paper.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :authenticate_account!
  def index
    @papers = Paper.all
  end

  def new
     @committee = Committee.find_by_id(params[:committee_id])
     @paper = Paper.new
  end
  
  def accept
    @paper = Paper.find_by_id(params[:id])
    respond_to do |format|
      @paper.update_attribute(:accepted, @paper.accepted = true)
      format.html { redirect_to @paper.committee }
    end
  end
  
  def decline
    @paper = Paper.find_by_id(params[:id])
    respond_to do |format|
      @paper.update_attribute(:accepted, @paper.accepted = false)
      format.html { redirect_to @paper.committee }
    end
  end
  
  def rate
    @papers = Paper.all
    @papers.each do |paper|
    @rate = 0.0
    @top = 0.0
    @bottem = 0.0
        paper.reviews.each do |review|
        @top += review.score * review.confidence
        @bottem += review.confidence
      end
      @rate = @top / @bottem
      paper.update_attribute(:rating, paper.rating = @rate)
    end
      respond_to do |format|
      format.html { redirect_to papers_path }
    end
  end
  
  def show
    @paper = Paper.find(params[:id])
  end
  
  def showid
    @papers = Paper.all
  end

  def create
  @paper = Paper.new(paper_params)
  @paper.authorid = current_account.id
  @paper.accepted = false
  @paper.rating = 0.0
  @state = false
    if @paper.save
      @paper.committee.tracks.each do |track| 
      if( track.userid == current_account.id && track.role == "Author" )
        @state = true
      end
      end
      if(@state)
        redirect_to @paper.committee.conference, notice: "The paper #{@paper.title} has been uploaded."
      else
        @paper.destroy
        redirect_to @paper.committee.conference, notice: "You are not an author of that committee. Paper not created."
      end
    else
      render "new"
    end
  end

  def destroy
   @paper = Paper.find(params[:id])
   @paper.reviews.each do |review| 
      if(review.paper == @paper)
        review.destroy
      end
   end
    @paper.destroy
    redirect_to papers_path, notice:  "The paper #{@paper.title} has been deleted."
  end
  
  private
  def paper_params
    params.require(:paper).permit(:title, :author, :attachment, :committee_id, :authorid, :accepted)
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.erb
<%= form_for([committee,paper]) do |f| %>
  <% if paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :committee_id %>
    <% if committee == nil %>
      <%= f.collection_select :committee_id, Committee.all, :id, :name %>
    <% else %>
      <%= f.select(:committee_id, options_for_select([[committee.name, committee.id]])) %>
    <% end %>
    <% f.text_field :committee_id %>
  </div>
  
  <div class="field">
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/papers/create.html.erb
<br />
<br />
<h1>Papers#create</h1>
<p>Find me in app/views/papers/create.html.erb</p>

app/views/papers/destroy.html.erb
<br />
<br />
<h1>Papers#destroy</h1>
<p>Find me in app/views/papers/destroy.html.erb</p>

app/views/papers/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<br />
<h1>Papers</h1>
<% if current_account.accountable_type == "SuperAccount" %>
<p><%= button_to "Rate",  rate_paper_path(id = 1), class: "btn btn-danger", data: { confirm: "Rate all the papers?"} %></p>

<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Conference</th>
      <th>Download Link</th>
      <th>Status</th>
      <th>Manage Paper</th>
      <th>Review Link</th>
      <th>Reviews</th>
      
    </tr>
  </thead>
  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.title %></td>
        <td><%= paper.author %></td>
        <td><%= link_to paper.committee.conference.name, paper.committee.conference %></td>
        <td><%= link_to "Download Paper", paper.attachment_url %></td>
        <td><%= paper.accepted %></td>
        <% if paper.authorid == current_account.id %>
        <td><%= button_to "Delete",  paper, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure that you wish to delete #{paper.title}?"} %></td>
        <% end %>
        <% if paper.authorid != current_account.id %>
        <td><%= button_to "Accept",  accept_paper_path(id = paper.id), class: "btn btn-danger", data: { confirm: "Are you sure that you wish to accept #{paper.title}?"} %></td>
        <% end %>
        <td><%= link_to "Review paper", new_review_path %></td>
        <td><%= link_to 'Reviews', paper %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>
<%= link_to "New Paper", new_paper_path, class: "btn btn-primary" %>
<% else %>
    <h3>Admins only.</h3>
<% end %>

app/views/papers/new.html.erb
<br />
<br />
<h1>New Paper</h1>

<%= render 'form', paper: @paper, committee: @committee %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<br />
<br />
<h1> Title: <%= @paper.title %></h1>
<h1> Author: <%= @paper.author %></h1>
<div class="col-lg-6">
    <iframe src=<%= @paper.attachment_url %> width="600" height="600" style="overflow:hidden;border: none;"> </iframe>
  </div>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Score</th>
      <th>Comments</th>
    </tr>
  </thead>
 <tbody> 
  <% @paper.reviews.each do |review| %>
     <tr>
       <td><%= review.score %></td>
       <td><%= review.comments %></td>
     </tr>
    <% end %>
 </tbody>
</table>
<%= link_to 'Back', @paper.committee %>

app/views/papers/showid.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<br />
<h1>Papers</h1>


<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Conference</th>
      <th>Download Link</th>
      <th>Status</th>
      <th>Delete Paper</th>
      <th>Reviews</t>
      
    </tr>
  </thead>
  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <% if paper.authorid == current_account.id %>
            <td><%= paper.title %></td>
            <td><%= paper.author %></td>
            <td><%= link_to paper.committee.name, paper.committee %></td>
            <td><%= link_to "Download Paper", paper.attachment_url %></td>
            <td><%= paper.accepted %></td>
            <td><%= button_to "Delete",  paper, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure that you wish to delete #{paper.title}?"} %></td>
            <td><%= link_to 'Reviews', paper %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
  
</table>