config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  namespace :admin do
    resources :accounts
    resources :conferences
    resources :papers
    resources :reviews
    resources :tracks
    resources :committees
    resources :users
    resources :super_accounts

    root to: "accounts#index"
  end

  resources :tracks
  resources :committees do
    get "showid", on: :member
    get "members", on: :member
    resources :papers, only: [:new, :create]
  end
  devise_for :accounts,  :controllers => { :registrations => 'registrations' }
  resources :users, only: [:edit, :update]
  resources :conferences do
    get "showid", on: :member
    resources :tracks, only: [:new, :create]
    resources :committees, only: [:new, :create]
  end
  resources :reviews do
    get "showid", on: :member
  end
  resources :papers do
    put 'accept', on: :member
    post 'accept', on: :member
    put 'decline', on: :member
    post 'decline', on: :member
    put 'rate', on: :member
    post 'rate', on: :member
    get "showid", on: :member
    resources :reviews, only: [:new, :create]
  end
  root "conferences#index"
  get "reviews/new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<br/>
<br/>
<br/>
<br/>
<br/>
<nav class="navbar navbar-inverse navbar-fixed-top">
   <div id="banner">
 <%= 'The UneasyChair' %>
 <span class="title"><%= @page_title %></span>
 </div>
  <div class="container">
    <div class="navbar-header navbar-right">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>
    <div class="collapse navbar-collapse navbar-right">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to "Home", conferences_path(spa: false) %></li>      
<li><%= link_to "Home (SPA)", conferences_path(spa: true) %></li>

<% if account_signed_in? %>
  <% if current_account.accountable_type == "SuperAccount" %>
        <li><%= link_to 'Admin Dashboard', admin_root_path %></li>   
        
    <% else %>
    <% if current_account.accountable_type != "SuperAccount" %>
    <li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Settings (<%= (current_account.accountable.name.nil? or current_account.accountable.name == "") ? "No Name" : current_account.accountable.name %>) <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            
            <%if current_account.accountable_type == "User" %>
                <li><%= link_to 'User Profile', edit_user_path(current_account.accountable_id) %></li>
                <li><%= link_to 'Your conferences', showid_conference_path(id = current_account.id) %></li>
                <li><%= link_to 'Your reviews', showid_review_path(id = current_account.id) %></li>
                <li><%= link_to 'Your committees', showid_committee_path(id = current_account.id) %></li>
                <li><%= link_to 'Tracks', tracks_path %></li>
                <li><td><%= link_to 'Your papers', showid_paper_path(id = current_account.id) %></td></li>
            <%end%>
            <li><%= link_to 'Account Settings', edit_account_registration_path %></li>
        </ul>
    </li>
 <% end %>
  <% end %>
    <li><%= link_to 'Sign out', destroy_account_session_path, :method=>'delete' %></li>

<% else %>
    <li><%= link_to 'Sign in', new_account_session_path %></li>
    <li><%= link_to 'Sign up', new_account_registration_path %></li>

<% end %>
<% if account_signed_in? %>
<% if current_account.accountable_type == "SuperAccount" %>
<li role="presentation" class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          Links <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
                <li><%= link_to 'Conference', conferences_path %></li>
                <li><%= link_to 'Review', reviews_path %></li>
                <li><%= link_to 'Paper', papers_path %></li>
        </ul>
    </li>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uneasy Chair</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
   <header>
      <%= render 'layouts/navigation' %>
  </header>
    
    </header>
    <div class="container">
      <%= yield %>
      <%= javascript_include_tag 'application' %>
    </div>
  </body>
</html>